services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/dreamdb
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "node src/seed.js && node src/app.js"

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--wiredTigerCacheSizeGB", "2"]
    deploy:
      resources:
        limits:
          memory: "4g"
        reservations:
          memory: "2g"

volumes:
  mongo-data: